name: gtsm3-era5-nrt-slm
channels:
  - conda-forge
dependencies:
  - python=3.10.6
  - xarray>=2022.6.0
  - netCDF4
  - dask
  - bottleneck
  - scipy
  - matplotlib>=3.5.3
  - cdsapi>=0.5.1
  - numpy>=1.23.2
  - cartopy>=0.21.0